version: "3"
services:
  angular:
    image: todoapp_angular
    ports:
      - "4200:4200"
  express:
    image: todoapp_express
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
